### ISSUE TITLE
Adjust the API of Reading::read_from_stream

### ISSUE THREAD

**Issue by shangsony** [ljedrz/pea2pea#1]
hi，this async fn read_from_stream<R: AsyncRead + Unpin + Send>(
&self,
addr: SocketAddr,
buffer: &mut [u8],
reader: &mut R,
carry: usize,
message_sender: &mpsc::Sender<Self::Message>,
) -> io::Result<usize> {

addr: SocketAddr, replace conn: Connection
the reason：To develop external applications you need not only messages, but also information about Connection

**Comment by ljedrz** [comment]
If I'm understanding correctly, this is a suggestion to replace the `addr: SocketAddr` param with a `conn: Connection` one? The `Connection` object is not readily available in that context, though, and it barely carries any additional useful information; what information about the connection are you missing for the purposes of manually implementing that function?

**Comment by shangsony** [comment]
I deployed two client nodes, but sent messages with send_direct_message, and the other client failed to receive messages

**Comment by ljedrz** [comment]
Did the recipient node enable the `Reading` protocol with `enable_reading()` before getting the message? Sending a direct message is one of the basic crate tests, so it should work just fine; please see e.g. https://github.com/ljedrz/pea2pea/blob/master/tests/messaging.rs#L83 for a short messaging example.

**Comment by shangsony** [comment]
I have enable_reading the send_direct_message and sending the message will not work, but send_broadcast will work

**Comment by shangsony** [comment]
Have you tested each node separately

**Comment by ljedrz** [comment]
Yes, I have, and I haven't detected any issues. I'll be happy to check out any minimal reproducible example if you can find some issue with the library. Ideally this would be a `#[tokio::test]` that should work (but for some reason isn't), and it can reuse any code from the existing test setups (ideally extending them in the end).

**Comment by ljedrz** [comment]
> I have enable_reading the send_direct_message and sending the message will not work, but send_broadcast will work
If broadcasting works, while `send_direct_message` doesn't, perhaps you're using the wrong address of the recipient?

**Comment by ljedrz** [comment]
Closing the issue due to inactivity; feel free to reopen if you'd like to provide more information so it can be considered further :ok_hand:.
