### ISSUE TITLE
why use OnceBox replace OnceCell?

### ISSUE THREAD

**Issue by theone-pang** [ljedrz/pea2pea#13]
why use OnceBox replace OnceCell?

**Comment by ljedrz** [comment]
It's likely to be faster to initialize, though the difference might be too small to be noticeable. 
Those values are set just once, when the protocols are enabled, so it seemed like a simpler solution. Do you have any specific concerns about this change?

**Comment by theone-pang** [comment]
i confuse with difference of OnceBox and  OnceCell

**Comment by ljedrz** [comment]
The difference is that `OnceBox` is non-blocking (which should be fine for the purposes of `pea2pea`). From the `once_cell` crate docs for `OnceBox`:
> If two threads race to initialize a type from the race module, they don’t block, execute initialization function together, but only one of them stores the result.

**Comment by ljedrz** [comment]
Closing the issue due to inactivity; feel free to reopen if there are any open points left.
