### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'attempt to add with overflow', network\src\known_peers.rs:49:13,bug

### ISSUE THREAD

**Issue by shangsony** [ljedrz/pea2pea#3]
thread 'tokio-runtime-worker' panicked at 'attempt to add with overflow', network\src\known_peers.rs:49:13
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:493
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\panicking.rs:92
   2: core::panicking::panic
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\panicking.rs:50
   3: network::known_peers::KnownPeers::register_failure
             at .\network\src\known_peers.rs:49
   4: network::protocols::reading::Reading::enable_reading::{{closure}}::{{closure}}<p2p::manger::PeerNetwork>
             at .\network\src\protocols\reading.rs:96
   5: core::future::from_generator::{{impl}}::poll<generator-1>
             at C:\Users\sonyshang\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\future\mod.rs:80
   6: tokio::runtime::task::core::{{impl}}::poll::{{closure}}<core::future::from_generator::GenFuture<generator-1>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\core.rs:235
   7: tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<core::future::from_generator::GenFuture<generator-1>>>::with_mut<tokio::runtime::task::core::Stage<core::future::from_generator::GenFuture<generator-1>>,core::task::poll::Poll<tup
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\loom\std\unsafe_cell.rs:14
   8: tokio::runtime::task::core::CoreStage<core::future::from_generator::GenFuture<generator-1>>::poll<core::future::from_generator::GenFuture<generator-1>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\core.rs:225
   9: tokio::runtime::task::harness::poll_future::{{closure}}<core::future::from_generator::GenFuture<generator-1>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\harness.rs:422
  10: std::panic::{{impl}}::call_once<core::task::poll::Poll<tuple<>>,closure-0>
             at C:\Users\sonyshang\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:344
  11: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,core::task::poll::Poll<tuple<>>>
             at C:\Users\sonyshang\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:379
  12: std::panicking::try::do_catch<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
  13: std::panicking::try<core::task::poll::Poll<tuple<>>,std::panic::AssertUnwindSafe<closure-0>>
             at C:\Users\sonyshang\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:343
  14: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,core::task::poll::Poll<tuple<>>>
             at C:\Users\sonyshang\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:431
  15: tokio::runtime::task::harness::poll_future<core::future::from_generator::GenFuture<generator-1>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\harness.rs:409
  16: tokio::runtime::task::harness::Harness<core::future::from_generator::GenFuture<generator-1>, alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>::poll_inner<core::future::from_generator::GenFuture<generator-1>,alloc::sync::Arc<tokio::runtime::t
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\harness.rs:89
  17: tokio::runtime::task::harness::Harness<core::future::from_generator::GenFuture<generator-1>, alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>::poll<core::future::from_generator::GenFuture<generator-1>,alloc::sync::Arc<tokio::runtime::thread_
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\harness.rs:59
  18: tokio::runtime::task::raw::poll<core::future::from_generator::GenFuture<generator-1>,alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\raw.rs:104
  19: tokio::runtime::task::raw::RawTask::poll
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\raw.rs:66
  20: tokio::runtime::task::Notified<alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>::run<alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\mod.rs:171
  21: tokio::runtime::thread_pool::worker::{{impl}}::run_task::{{closure}}
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\thread_pool\worker.rs:349
  22: tokio::coop::with_budget::{{closure}}<core::result::Result<alloc::boxed::Box<tokio::runtime::thread_pool::worker::Core, alloc::alloc::Global>, tuple<>>,closure-0>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\coop.rs:106
  23: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::try_with<core::cell::Cell<tokio::coop::Budget>,closure-0,core::result::Result<alloc::boxed::Box<tokio::runtime::thread_pool::worker::Core, alloc::alloc::Global>, tuple<>>>
             at C:\Users\sonyshang\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:272
  24: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::with<core::cell::Cell<tokio::coop::Budget>,closure-0,core::result::Result<alloc::boxed::Box<tokio::runtime::thread_pool::worker::Core, alloc::alloc::Global>, tuple<>>>
             at C:\Users\sonyshang\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:248
  25: tokio::coop::with_budget
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\coop.rs:99
  26: tokio::coop::budget
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\coop.rs:76
  27: tokio::runtime::thread_pool::worker::Context::run_task
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\thread_pool\worker.rs:348
  28: tokio::runtime::thread_pool::worker::Context::run
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\thread_pool\worker.rs:318
  29: tokio::runtime::thread_pool::worker::run::{{closure}}
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\thread_pool\worker.rs:303
  30: tokio::macros::scoped_tls::ScopedKey<tokio::runtime::thread_pool::worker::Context>::set<tokio::runtime::thread_pool::worker::Context,closure-0,tuple<>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\macros\scoped_tls.rs:61
  31: tokio::runtime::thread_pool::worker::run
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\thread_pool\worker.rs:300
  32: tokio::runtime::thread_pool::worker::{{impl}}::launch::{{closure}}
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\thread_pool\worker.rs:279
  33: tokio::runtime::blocking::task::{{impl}}::poll<closure-0,tuple<>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\blocking\task.rs:42
  34: tokio::runtime::task::core::{{impl}}::poll::{{closure}}<tokio::runtime::blocking::task::BlockingTask<closure-0>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\core.rs:235
  35: tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask<closure-0>>>::with_mut<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask<closure-0>>,core::task::poll::Po
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\loom\std\unsafe_cell.rs:14
  36: tokio::runtime::task::core::CoreStage<tokio::runtime::blocking::task::BlockingTask<closure-0>>::poll<tokio::runtime::blocking::task::BlockingTask<closure-0>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\core.rs:225
  37: tokio::runtime::task::harness::poll_future::{{closure}}<tokio::runtime::blocking::task::BlockingTask<closure-0>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\harness.rs:422
  38: std::panic::{{impl}}::call_once<core::task::poll::Poll<tuple<>>,closure-0>
             at C:\Users\sonyshang\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:344
  39: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,core::task::poll::Poll<tuple<>>>
             at C:\Users\sonyshang\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:379
  40: tokio::runtime::thread_pool::idle::{{impl}}::from
  41: std::panicking::try<core::task::poll::Poll<tuple<>>,std::panic::AssertUnwindSafe<closure-0>>
             at C:\Users\sonyshang\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:343
  42: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,core::task::poll::Poll<tuple<>>>
             at C:\Users\sonyshang\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:431
  43: tokio::runtime::task::harness::poll_future<tokio::runtime::blocking::task::BlockingTask<closure-0>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\harness.rs:409
  44: tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<closure-0>, tokio::runtime::blocking::schedule::NoopSchedule>::poll_inner<tokio::runtime::blocking::task::BlockingTask<closure-0>,tokio::runtime::blocking::schedule::NoopS
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\harness.rs:89
  45: tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<closure-0>, tokio::runtime::blocking::schedule::NoopSchedule>::poll<tokio::runtime::blocking::task::BlockingTask<closure-0>,tokio::runtime::blocking::schedule::NoopSchedul
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\harness.rs:59
  46: tokio::runtime::task::raw::poll<tokio::runtime::blocking::task::BlockingTask<closure-0>,tokio::runtime::blocking::schedule::NoopSchedule>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\raw.rs:104
  47: tokio::runtime::task::raw::RawTask::poll
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\raw.rs:66
  48: tokio::runtime::task::Notified<tokio::runtime::blocking::schedule::NoopSchedule>::run<tokio::runtime::blocking::schedule::NoopSchedule>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\mod.rs:171
  49: tokio::runtime::blocking::pool::Inner::run
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\blocking\pool.rs:278
  50: tokio::runtime::blocking::pool::{{impl}}::spawn_thread::{{closure}}
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\blocking\pool.rs:258
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'tokio-runtime-worker' panicked at 'attempt to add with overflow', network\src\known_peers.rs:49:13
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:493
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\panicking.rs:92
   2: core::panicking::panic
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\panicking.rs:50
   3: network::known_peers::KnownPeers::register_failure
             at .\network\src\known_peers.rs:49
   4: network::protocols::reading::Reading::enable_reading::{{closure}}::{{closure}}<p2p::manger::PeerNetwork>
             at .\network\src\protocols\reading.rs:96
   5: core::future::from_generator::{{impl}}::poll<generator-1>
             at C:\Users\sonyshang\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\future\mod.rs:80
   6: tokio::runtime::task::core::{{impl}}::poll::{{closure}}<core::future::from_generator::GenFuture<generator-1>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\core.rs:235
   7: tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<core::future::from_generator::GenFuture<generator-1>>>::with_mut<tokio::runtime::task::core::Stage<core::future::from_generator::GenFuture<generator-1>>,core::task::poll::Poll<tup
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\loom\std\unsafe_cell.rs:14
   8: tokio::runtime::task::core::CoreStage<core::future::from_generator::GenFuture<generator-1>>::poll<core::future::from_generator::GenFuture<generator-1>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\core.rs:225
   9: tokio::runtime::task::harness::poll_future::{{closure}}<core::future::from_generator::GenFuture<generator-1>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\harness.rs:422
  10: std::panic::{{impl}}::call_once<core::task::poll::Poll<tuple<>>,closure-0>
             at C:\Users\sonyshang\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:344
  11: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,core::task::poll::Poll<tuple<>>>
             at C:\Users\sonyshang\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:379
  12: std::panicking::try::do_catch<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
  13: std::panicking::try<core::task::poll::Poll<tuple<>>,std::panic::AssertUnwindSafe<closure-0>>
             at C:\Users\sonyshang\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:343
  14: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,core::task::poll::Poll<tuple<>>>
             at C:\Users\sonyshang\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:431
  15: tokio::runtime::task::harness::poll_future<core::future::from_generator::GenFuture<generator-1>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\harness.rs:409
  16: tokio::runtime::task::harness::Harness<core::future::from_generator::GenFuture<generator-1>, alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>::poll_inner<core::future::from_generator::GenFuture<generator-1>,alloc::sync::Arc<tokio::runtime::t
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\harness.rs:89
  17: tokio::runtime::task::harness::Harness<core::future::from_generator::GenFuture<generator-1>, alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>::poll<core::future::from_generator::GenFuture<generator-1>,alloc::sync::Arc<tokio::runtime::thread_
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\harness.rs:59
  18: tokio::runtime::task::raw::poll<core::future::from_generator::GenFuture<generator-1>,alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\raw.rs:104
  19: tokio::runtime::task::raw::RawTask::poll
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\raw.rs:66
  20: tokio::runtime::task::Notified<alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>::run<alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\mod.rs:171
  21: tokio::runtime::thread_pool::worker::{{impl}}::run_task::{{closure}}
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\thread_pool\worker.rs:349
  22: tokio::coop::with_budget::{{closure}}<core::result::Result<alloc::boxed::Box<tokio::runtime::thread_pool::worker::Core, alloc::alloc::Global>, tuple<>>,closure-0>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\coop.rs:106
  23: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::try_with<core::cell::Cell<tokio::coop::Budget>,closure-0,core::result::Result<alloc::boxed::Box<tokio::runtime::thread_pool::worker::Core, alloc::alloc::Global>, tuple<>>>
             at C:\Users\sonyshang\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:272
  24: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::with<core::cell::Cell<tokio::coop::Budget>,closure-0,core::result::Result<alloc::boxed::Box<tokio::runtime::thread_pool::worker::Core, alloc::alloc::Global>, tuple<>>>
             at C:\Users\sonyshang\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:248
  25: tokio::coop::with_budget
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\coop.rs:99
  26: tokio::coop::budget
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\coop.rs:76
  27: tokio::runtime::thread_pool::worker::Context::run_task
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\thread_pool\worker.rs:348
  28: tokio::runtime::thread_pool::worker::Context::run
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\thread_pool\worker.rs:325
  29: tokio::runtime::thread_pool::worker::run::{{closure}}
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\thread_pool\worker.rs:303
  30: tokio::macros::scoped_tls::ScopedKey<tokio::runtime::thread_pool::worker::Context>::set<tokio::runtime::thread_pool::worker::Context,closure-0,tuple<>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\macros\scoped_tls.rs:61
  31: tokio::runtime::thread_pool::worker::run
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\thread_pool\worker.rs:300
  32: tokio::runtime::thread_pool::worker::{{impl}}::launch::{{closure}}
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\thread_pool\worker.rs:279
  33: tokio::runtime::blocking::task::{{impl}}::poll<closure-0,tuple<>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\blocking\task.rs:42
  34: tokio::runtime::task::core::{{impl}}::poll::{{closure}}<tokio::runtime::blocking::task::BlockingTask<closure-0>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\core.rs:235
  35: tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask<closure-0>>>::with_mut<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask<closure-0>>,core::task::poll::Po
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\loom\std\unsafe_cell.rs:14
  36: tokio::runtime::task::core::CoreStage<tokio::runtime::blocking::task::BlockingTask<closure-0>>::poll<tokio::runtime::blocking::task::BlockingTask<closure-0>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\core.rs:225
  37: tokio::runtime::task::harness::poll_future::{{closure}}<tokio::runtime::blocking::task::BlockingTask<closure-0>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\harness.rs:422
  38: std::panic::{{impl}}::call_once<core::task::poll::Poll<tuple<>>,closure-0>
             at C:\Users\sonyshang\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:344
  39: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,core::task::poll::Poll<tuple<>>>
             at C:\Users\sonyshang\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:379
  40: tokio::runtime::thread_pool::idle::{{impl}}::from
  41: std::panicking::try<core::task::poll::Poll<tuple<>>,std::panic::AssertUnwindSafe<closure-0>>
             at C:\Users\sonyshang\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:343
  42: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,core::task::poll::Poll<tuple<>>>
             at C:\Users\sonyshang\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:431
  43: tokio::runtime::task::harness::poll_future<tokio::runtime::blocking::task::BlockingTask<closure-0>>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\harness.rs:409
  44: tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<closure-0>, tokio::runtime::blocking::schedule::NoopSchedule>::poll_inner<tokio::runtime::blocking::task::BlockingTask<closure-0>,tokio::runtime::blocking::schedule::NoopS
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\harness.rs:89
  45: tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<closure-0>, tokio::runtime::blocking::schedule::NoopSchedule>::poll<tokio::runtime::blocking::task::BlockingTask<closure-0>,tokio::runtime::blocking::schedule::NoopSchedul
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\harness.rs:59
  46: tokio::runtime::task::raw::poll<tokio::runtime::blocking::task::BlockingTask<closure-0>,tokio::runtime::blocking::schedule::NoopSchedule>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\raw.rs:104
  47: tokio::runtime::task::raw::RawTask::poll
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\raw.rs:66
  48: tokio::runtime::task::Notified<tokio::runtime::blocking::schedule::NoopSchedule>::run<tokio::runtime::blocking::schedule::NoopSchedule>
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\task\mod.rs:171
  49: tokio::runtime::blocking::pool::Inner::run
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\blocking\pool.rs:278
  50: tokio::runtime::blocking::pool::{{impl}}::spawn_thread::{{closure}}
             at C:\Users\sonyshang\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\tokio-1.5.0\src\runtime\blocking\pool.rs:258
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by shangsony** [comment]
![image](https://user-images.githubusercontent.com/19890858/115838910-ba992300-a44c-11eb-9db8-5a6a600e382d.png)
thread 'tokio-runtime-worker' panicked at 'attempt to add with overflow', network\src\known_peers.rs:49:13
stack backtrace:

![image](https://user-images.githubusercontent.com/19890858/115839041-d7355b00-a44c-11eb-9cf4-51a67e0d1238.png)
.\network\src\protocols\reading.rs:96

   0: std::panicking::begin_panic_handler
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:493
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\panicking.rs:92
   2: core::panicking::panic
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\panicking.rs:50
   3: network::known_peers::KnownPeers::register_failure
             at .\network\src\known_peers.rs:49
   4: network::protocols::reading::Reading::enable_reading::{{closure}}::{{closure}}<p2p::manger::PeerNetwork>
             at .\network\src\protocols\reading.rs:96

**Comment by ljedrz** [comment]
I usually kicked nodes after a specific number of failures, but there's no reason why it shouldn't be a saturating addition in order to avoid an overflow if that's not in place. I'll adjust it shortly :+1:.

**Comment by ljedrz** [comment]
Fixed in `0.19.1`; note that a peer with that many registered failures is likely faulty/malicious - you might want to drop those using some periodically running maintenance task.
