### ISSUE TITLE
no available capacity  - protocols::writing network/src/protocols/writing.rs

### ISSUE THREAD

**Issue by shangsony** [ljedrz/pea2pea#7]
the error is code:
![image](https://user-images.githubusercontent.com/19890858/150460702-83245b03-c1d5-458f-a230-bbe862604c17.png)
the error info:
![middle_img_v2_b5d21d06-e9ac-49e5-a761-140e00b14b2g](https://user-images.githubusercontent.com/19890858/150460706-23bed5a4-d22e-4d91-81bc-b7b299ca2508.png)
can't send a message to 115.231.21.48:19333: no available capacity  - network::protocols::writing network/src/protocols/writing.rs -line:144

so i suggest will mpsc::channel::<..>(64) replace mpsc::unbounded_channel()

**Comment by ljedrz** [comment]
The depth of per-connection outbound channels is specified by [outbound_queue_depth](https://docs.rs/pea2pea/latest/pea2pea/struct.Config.html#structfield.outbound_queue_depth), which is part of the [Config](https://docs.rs/pea2pea/latest/pea2pea/struct.Config.html) struct. While its default value is `64`, you are free to set it to something greater when you're creating your `Node`. Using unbounded channels is undesirable, as it could cause memory use to grow in an uncontrolled fashion and possibly hide the fact that the messages are taking too long to be sent, which might indicate an issue with the implementation.

**Comment by ljedrz** [comment]
Closing the issue due to lack of activity and arguments against the rationale behind the current logic.
